# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "amazon_seller_central"
  s.version = "0.2.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["optoro"]
  s.date = "2013-05-01"
  s.description = "This gem is intended to wrap Amazon's SellerCentral pages with a Ruby API. Currently this gem supports accessing buyer feedback only."
  s.email = "dev@optoro.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "amazon_seller_central.gemspec",
    "lib/amazon_seller_central.rb",
    "lib/amazon_seller_central/configuration.rb",
    "lib/amazon_seller_central/feedback.rb",
    "lib/amazon_seller_central/feedback_page.rb",
    "lib/amazon_seller_central/inventory.rb",
    "lib/amazon_seller_central/inventory_page.rb",
    "lib/amazon_seller_central/listing.rb",
    "lib/amazon_seller_central/listing_set.rb",
    "lib/amazon_seller_central/mechanizer.rb",
    "lib/amazon_seller_central/order.rb",
    "lib/amazon_seller_central/orders_page.rb",
    "lib/amazon_seller_central/page.rb",
    "lib/amazon_seller_central/payment.rb",
    "lib/amazon_seller_central/payments_page.rb",
    "spec/amazon_seller_central_spec.rb",
    "spec/lib/feedback_page_spec.rb",
    "spec/lib/feedback_spec.rb",
    "spec/lib/inventory_page_spec.rb",
    "spec/lib/inventory_spec.rb",
    "spec/lib/listing_set_spec.rb",
    "spec/lib/listing_spec.rb",
    "spec/lib/mechanizer_spec.rb",
    "spec/lib/orders_page_spec.rb",
    "spec/lib/payments_page_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/page_body_regexen.rb",
    "spec/support/page_examples.rb",
    "spec/support/sample_pages.rb",
    "spec/support/sample_pages/Feedback Manager.html",
    "spec/support/sample_pages/Feedback Page 1.html",
    "spec/support/sample_pages/Feedback Page 2.html",
    "spec/support/sample_pages/Feedback Page Last.html",
    "spec/support/sample_pages/Manage Orders.html",
    "spec/support/sample_pages/Payments Page.html",
    "spec/support/sample_pages/Seller Central Homepage.html",
    "spec/support/sample_pages/Seller Central Redirect.html",
    "spec/support/sample_pages/Seller Central.html",
    "spec/support/sample_pages/Settlement Payment Reports 1.html",
    "spec/support/sample_pages/Settlement Payment Reports 2.html",
    "spec/support/sample_pages/another_listings_page.html",
    "spec/support/sample_pages/listings_last_page.html",
    "spec/support/sample_pages/listings_page_1.html",
    "spec/support/sample_pages/listings_page_2.html",
    "spec/support/sample_pages/update_inventory_result_from_last_page.html",
    "spec/support/sample_pages/update_inventory_result_from_page_1.html",
    "spec/support/sample_pages/update_inventory_result_from_page_2.html"
  ]
  s.homepage = "http://github.com/optoro/amazon_seller_central"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby API to access Amazon's SellerCentral"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<rb-inotify>, [">= 0.8.5"])
      s.add_development_dependency(%q<libnotify>, [">= 0"])
      s.add_development_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<faker>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
    else
      s.add_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<rb-inotify>, [">= 0.8.5"])
      s.add_dependency(%q<libnotify>, [">= 0"])
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<faker>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
    end
  else
    s.add_dependency(%q<mechanize>, [">= 1.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<rb-inotify>, [">= 0.8.5"])
    s.add_dependency(%q<libnotify>, [">= 0"])
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<faker>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
  end
end

